language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 4
  - 5
  - 6

after_script:
  - npm run coverage

notifications:
  slack:
    secure: "Tr61iRUdZXNNwwoxlAio/+R2v8ib+DWXpCkAHfjDVmE6dVcrdjmgnUI7CFsALyah9QB7no0V4rWatjVJTLTi6dhgrxXUlFFwkj57ffPdTIIgV2UkvY6FBhjesFh3YLuGev7xebFrHHJVRyRoi3gZBhVB4yWElKCiccjZH9USmuk="
